

\chapter{The Core of a Traditional Course}






In this chapter, we will briefly review the commands and functions needed
to analyze data from a more traditional introductory statistics course.
We will use data from the HELP study: a randomized trial of a novel 
way to link at-risk subjects with primary care.  More information on the
dataset can be found in section \ref{sec:help}.

Some data management is needed by students (and more by instructors).  This
material is reviewed in section \ref{sec:manipulatingData}.

Since the selection and order of topics can vary greatly from 
textbook to textbook and instructor to instructor, we have chosen to 
organize this material by the kind of data being analyzed.  This should make
it straightforward to find what you are looking for even if you present 
things in a different order.  This is also a good organizational template
to give your students to help them keep straight ``what to do when".

\InstructorNote{Just what is the \emph{traditional course}, anyways?}
It's worth noting how we teach the ``Traditional Course'', which, contrary
to rumor, some of us do on occasion.  Nick has used the 5th edition of
Moore and McCabe \cite{moor:mcca:2006}, where he introduces least squares 
regression at the end of the first week of a semester, and multiple regression
(purely descriptively) at the end of the second week.  Design is the next
main topic, then a brutally pruned intro to probability and sampling distributions.
Interval estimation and testing are introduced in one or two settings, then 
the class returns to inference for multiple regression.  While students are working
on projects involving a multiple linear regression model with 2 predictors,
some categorical data analysis is covered.

\authNote{Danny and/or Randy: interested in chiming in?}

\section{One Quantitative Variable}

\subsection{Numerical Summaries}

\R\ includes a number of commands to numerically summarize variables.
These include the capability of calculating the mean, standard deviation,
variance, median, five number summary, intra-quartile range (IQR) as well as arbitrary quantiles.  We will
illustrate these using the CESD (Center for Epidemiologic Studies - Depression)
measure of depressive symptoms.  To improve the legibility of output,
we will also set the default number of digits to display to a more reasonable
level (see {\tt ?options} for more configuration possibilities).

\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{options}\hlkeyword{(}\hlargument{digits}{\ }\hlargument{=}{\ }\hlnumber{3}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlfunctioncall{mean}\hlkeyword{(}\hlsymbol{HELP}\hlkeyword{\usebox{\hlnormalsizeboxdollar}}\hlsymbol{cesd}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
mean 
32.8 
\end{verbatim}
\end{kframe}}
\end{knitrout}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{sd}\hlkeyword{(}\hlsymbol{HELP}\hlkeyword{\usebox{\hlnormalsizeboxdollar}}\hlsymbol{cesd}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
  sd 
12.5 
\end{verbatim}
\end{kframe}}
\end{knitrout}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{sd}\hlkeyword{(}\hlsymbol{HELP}\hlkeyword{\usebox{\hlnormalsizeboxdollar}}\hlsymbol{cesd}\hlkeyword{)}\hlkeyword{\usebox{\hlnormalsizeboxhat}}\hlnumber{2}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
 sd 
157 
\end{verbatim}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{var}\hlkeyword{(}\hlsymbol{HELP}\hlkeyword{\usebox{\hlnormalsizeboxdollar}}\hlsymbol{cesd}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
var 
157 
\end{verbatim}
\end{kframe}}
\end{knitrout}


It is also straightforward to calculate quantiles of the distribution.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{median}\hlkeyword{(}\hlsymbol{HELP}\hlkeyword{\usebox{\hlnormalsizeboxdollar}}\hlsymbol{cesd}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
median 
    34 
\end{verbatim}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{five}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlfunctioncall{fivenum}\hlkeyword{(}\hlsymbol{HELP}\hlkeyword{\usebox{\hlnormalsizeboxdollar}}\hlsymbol{cesd}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlsymbol{five}{\ }{\ }\hlcomment{\usebox{\hlnormalsizeboxhash}{\ }display{\ }the{\ }object{\ }(vector{\ }of{\ }length{\ }5)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
[1]  1 25 34 41 60
\end{verbatim}
\end{kframe}}
\end{knitrout}

The user can interact with the objects created by these
functions to calculate the IQR (or the built-in a function can generate this directly).
\Caution{Note that the hinges are not necessarily the same as the
quartiles, due to interpolation in small datasets}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{five}\hlkeyword{[}\hlnumber{4}\hlkeyword{]}{\ }\hlkeyword{-}{\ }\hlsymbol{five}\hlkeyword{[}\hlnumber{2}\hlkeyword{]}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
[1] 16
\end{verbatim}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{IQR}\hlkeyword{(}\hlsymbol{HELP}\hlkeyword{\usebox{\hlnormalsizeboxdollar}}\hlsymbol{cesd}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
[1] 16
\end{verbatim}
\end{kframe}}
\end{knitrout}



\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{quantile}\hlkeyword{(}\hlsymbol{HELP}\hlkeyword{\usebox{\hlnormalsizeboxdollar}}\hlsymbol{cesd}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
  0%  25%  50%  75% 100% 
   1   25   34   41   60 
\end{verbatim}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{quantile}\hlkeyword{(}\hlsymbol{HELP}\hlkeyword{\usebox{\hlnormalsizeboxdollar}}\hlsymbol{cesd}\hlkeyword{,}{\ }\hlfunctioncall{c}\hlkeyword{(}\hlnumber{0.25}\hlkeyword{,}{\ }\hlnumber{0.5}\hlkeyword{)}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
25% 50% 
 25  34 
\end{verbatim}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{favstats}\hlkeyword{(}\hlsymbol{HELP}\hlkeyword{\usebox{\hlnormalsizeboxdollar}}\hlsymbol{cesd}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
   0%   25%   50%   75%  100%  mean    sd   var 
  1.0  25.0  34.0  41.0  60.0  32.8  12.5 156.6 
\end{verbatim}
\end{kframe}}
\end{knitrout}


By default, the 
\function{quantile()} function displays the quartiles, but can be given
a vector of quantiles to display.  Finally, the \function{favstats()}
function in the \pkg{mosaic} package provides a concise summary of 
many useful statistics.


\subsection{Graphical Summaries}
The \function{histogram()} function is used to create a histogram.
Here we use the formula interface (as discussed in section \ref{sec:formula}) to
specify that we want a histogram of the CESD scores.

\vspace{-4mm}
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{histogram}\hlkeyword{(}\hlkeyword{\urltilda{}}\hlsymbol{cesd}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}


\centering{}\includegraphics{figures/fig-cesd-hist} 

\end{kframe}}
\end{knitrout}

\end{center}


In the HELP dataset, approximately one quarter of the subjects are female.  
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{with}\hlkeyword{(}\hlsymbol{HELP}\hlkeyword{,}{\ }\hlfunctioncall{table}\hlkeyword{(}\hlsymbol{sex}\hlkeyword{)}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
sex
female   male 
   107    346 
\end{verbatim}
\end{kframe}}
\end{knitrout}

It is straightforward to restrict our attention to just those subjects.
If we are going to do many things with a subset of our data, it may be easiest
to make a new data frame containing only the cases we are interested in.
The \function{subset()} function can generate a new data frame containing
just the women or just the men  (see also section \ref{sec:subsets}).  Once this is created, we
used the \function{stem()} function to create a stem and leaf plot.
\Caution{Note that the equality operator is \emph{two} equal signs}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{female}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlfunctioncall{subset}\hlkeyword{(}\hlsymbol{HELP}\hlkeyword{,}{\ }\hlsymbol{sex}{\ }=={\ }\hlstring{"{}female"{}}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlsymbol{male}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlfunctioncall{subset}\hlkeyword{(}\hlsymbol{HELP}\hlkeyword{,}{\ }\hlsymbol{sex}{\ }=={\ }\hlstring{"{}male"{}}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlfunctioncall{stem}\hlkeyword{(}\hlsymbol{female}\hlkeyword{\usebox{\hlnormalsizeboxdollar}}\hlsymbol{cesd}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}

  The decimal point is 1 digit(s) to the right of the |

  0 | 3
  0 | 567
  1 | 3
  1 | 555589999
  2 | 123344
  2 | 66889999
  3 | 0000233334444
  3 | 5556666777888899999
  4 | 00011112222334
  4 | 555666777889
  5 | 011122222333444
  5 | 67788
  6 | 0

\end{verbatim}
\end{kframe}}
\end{knitrout}


The plotting functions in the \pkg{lattice} package have a \option{subset}
argument that allows us to select only a portion of the data.
This can be handy for explaration and avoids the need to make (and name)
various subsets.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{histogram}\hlkeyword{(}\hlkeyword{\urltilda{}}\hlsymbol{cesd}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{,}{\ }\hlargument{subset}{\ }\hlargument{=}{\ }\hlsymbol{sex}{\ }=={\ }\hlstring{"{}female"{}}\hlkeyword{)}{\ }{\ }\hlcomment{\usebox{\hlnormalsizeboxhash}{\ }notice{\ }the{\ }quotes}\mbox{}
\normalfont
\end{flushleft}


\centering{}\includegraphics{figures/fig-women-cesd-hist} 

\end{kframe}}
\end{knitrout}


Alternatively, we can make side-by-side plots to compare multiple subsets.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{histogram}\hlkeyword{(}\hlkeyword{\urltilda{}}\hlsymbol{cesd}{\ }\hlkeyword{|}{\ }\hlsymbol{sex}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}


\centering{}\includegraphics{figures/fig-cesd-male-female} 

\end{kframe}}
\end{knitrout}


\begin{problem}
Using the HELP dataset, 
create side by side boxplots of the CESD scores by substance abuse
group, just for the male subjects.
\end{problem}
\begin{solution}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{bwplot}\hlkeyword{(}\hlsymbol{cesd}{\ }\hlkeyword{\urltilda{}}{\ }\hlsymbol{substance}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{,}{\ }\hlargument{subset}{\ }\hlargument{=}{\ }\hlsymbol{sex}{\ }=={\ }\hlstring{"{}male"{}}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}


\centering{}\includegraphics{figures/fig-subsmale} 

\end{kframe}}
\end{knitrout}

\end{solution}

The \function{dotPlot()} function is used to create a dotplot (a la Fathom).

\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{histogram}\hlkeyword{(}\hlkeyword{\urltilda{}}\hlsymbol{cesd}\hlkeyword{,}{\ }\hlargument{nint}{\ }\hlargument{=}{\ }\hlnumber{20}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{female}\hlkeyword{)}{\ }{\ }\hlcomment{\usebox{\hlnormalsizeboxhash}{\ }was{\ }dotPlot}\mbox{}
\normalfont
\end{flushleft}


\centering{}\includegraphics{figures/fig-cesd-dot} 

\end{kframe}}
\end{knitrout}

\end{center}

We could also have made our subset ``on the fly'', just for the purposes of graphing:
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{histogram}\hlkeyword{(}\hlkeyword{\urltilda{}}\hlsymbol{cesd}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{,}{\ }\hlargument{subset}{\ }\hlargument{=}{\ }\hlkeyword{(}\hlsymbol{sex}{\ }=={\ }\hlstring{"{}female"{}}\hlkeyword{)}\hlkeyword{)}{\ }{\ }\hlcomment{\usebox{\hlnormalsizeboxhash}{\ }was{\ }dotPlot}\mbox{}
\normalfont
\end{flushleft}


\centering{}\includegraphics{figures/fig-cesd-dot2} 

\end{kframe}}
\end{knitrout}

\end{center}

Or we could make side-by-side dotplots of men and women:
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{histogram}\hlkeyword{(}\hlkeyword{\urltilda{}}\hlsymbol{cesd}{\ }\hlkeyword{|}{\ }\hlsymbol{sex}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{)}{\ }{\ }\hlcomment{\usebox{\hlnormalsizeboxhash}{\ }was{\ }dotPlot}\mbox{}
\normalfont
\end{flushleft}


\centering{}\includegraphics{figures/fig-cesd-dot3} 

\end{kframe}}
\end{knitrout}

\end{center}


\subsection{Density Curves}

One disadvantage of histograms is that they can be sensitive to the choice of the
number of bins.  Another display to consider is a density curve.
\FoodForThought{Density plots are also sensitive to certain choices.  If your density plot
is too jagged or too smooth, try adjusting the \option{adjust} argument (larger than 1 for
smoother plots, less than 1 for more jagged plots.}

\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{densityplot}\hlkeyword{(}\hlkeyword{\urltilda{}}\hlsymbol{cesd}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{female}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlfunctioncall{ladd}\hlkeyword{(}\hlfunctioncall{grid.text}\hlkeyword{(}\hlargument{x}{\ }\hlargument{=}{\ }\hlnumber{0.2}\hlkeyword{,}{\ }\hlargument{y}{\ }\hlargument{=}{\ }\hlnumber{0.8}\hlkeyword{,}{\ }\hlstring{"{}only{\ }females"{}}\hlkeyword{)}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlfunctioncall{ladd}\hlkeyword{(}\hlfunctioncall{panel.mathdensity}\hlkeyword{(}\hlargument{args}{\ }\hlargument{=}{\ }\hlfunctioncall{list}\hlkeyword{(}\hlargument{mean}{\ }\hlargument{=}{\ }\hlfunctioncall{mean}\hlkeyword{(}\hlsymbol{female}\hlkeyword{\usebox{\hlnormalsizeboxdollar}}\hlsymbol{cesd}\hlkeyword{)}\hlkeyword{,}{\ }\hlargument{sd}{\ }\hlargument{=}{\ }\hlfunctioncall{sd}\hlkeyword{(}\hlsymbol{female}\hlkeyword{\usebox{\hlnormalsizeboxdollar}}\hlsymbol{cesd}\hlkeyword{)}\hlkeyword{)}\hlkeyword{,}\hspace*{\fill}\\
\hlstd{}{\ }{\ }{\ }{\ }\hlargument{col}{\ }\hlargument{=}{\ }\hlstring{"{}red"{}}\hlkeyword{)}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}


\centering{}\includegraphics{figures/fig-dens1} 

\end{kframe}}
\end{knitrout}

\end{center}

The most famous density curve is a normal distribution.  The \function{xpnorm()} function
displays the probability that a random variable is less than the first argument, for a 
normal distribution with mean given by the second argument and standard deviation by the 
third.  More information about probability distributions can 
be found in section \ref{sec:probability}.

\subsection{Normal Distributions}
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{xpnorm}\hlkeyword{(}\hlnumber{1.96}\hlkeyword{,}{\ }\hlnumber{0}\hlkeyword{,}{\ }\hlnumber{1}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}

If X ~ N(0,1), then 

	P(X <= 1.96) = P(Z <= 1.96) = 0.975
	P(X >  1.96) = P(Z >  1.96) = 0.025

\end{verbatim}
\begin{verbatim}
[1] 0.975
\end{verbatim}


\centering{}\includegraphics{figures/fig-norm11} \includegraphics{figures/fig-norm12} 

\end{kframe}}
\end{knitrout}

\end{center}

\subsection{Inference for a single sample}

We can calculate a 95\% confindence interval for the mean CESD 
score for females by using a t-test:
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{t.test}\hlkeyword{(}\hlsymbol{female}\hlkeyword{\usebox{\hlnormalsizeboxdollar}}\hlsymbol{cesd}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}

	One Sample t-test

data:  female$cesd 
t = 29.3, df = 106, p-value < 2.2e-16
alternative hypothesis: true mean is not equal to 0 
95 percent confidence interval:
 34.4 39.4 
sample estimates:
mean of x 
     36.9 

\end{verbatim}
\end{kframe}}
\end{knitrout}


But it's also straightforward to calculate this using a bootstrap.
The statistic that we want to resample is the mean.  
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{with}\hlkeyword{(}\hlsymbol{female}\hlkeyword{,}{\ }\hlfunctioncall{mean}\hlkeyword{(}\hlsymbol{cesd}\hlkeyword{)}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
mean 
36.9 
\end{verbatim}
\end{kframe}}
\end{knitrout}


One resampling trial can be carried out with
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{with}\hlkeyword{(}\hlfunctioncall{resample}\hlkeyword{(}\hlsymbol{female}\hlkeyword{)}\hlkeyword{,}{\ }\hlfunctioncall{mean}\hlkeyword{(}\hlsymbol{cesd}\hlkeyword{)}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
mean 
  38 
\end{verbatim}
\end{kframe}}
\end{knitrout}

Even though a single trial is of little use, it's a nice idea to have
students do the calculation to show that they are getting a different
(usually!) result than without resampling.

Now conduct 1000 resampling trials, saving the results in an object
called \texttt{trials}:
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{trials}{\ }\hlassignement{=}{\ }\hlfunctioncall{do}\hlkeyword{(}\hlnumber{1000}\hlkeyword{)}{\ }\hlkeyword{*}{\ }\hlfunctioncall{with}\hlkeyword{(}\hlfunctioncall{resample}\hlkeyword{(}\hlsymbol{female}\hlkeyword{)}\hlkeyword{,}{\ }\hlfunctioncall{mean}\hlkeyword{(}\hlsymbol{cesd}\hlkeyword{)}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlfunctioncall{quantile}\hlkeyword{(}\hlsymbol{trials}\hlkeyword{\usebox{\hlnormalsizeboxdollar}}\hlsymbol{mean}\hlkeyword{,}{\ }\hlfunctioncall{c}\hlkeyword{(}\hlnumber{0.025}\hlkeyword{,}{\ }\hlnumber{0.975}\hlkeyword{)}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
 2.5% 97.5% 
 34.7  39.1 
\end{verbatim}
\end{kframe}}
\end{knitrout}


\section{One Categorical Variable}

\subsection{Numerical Summaries}

The \function{xtabs()}, \function{perctable()} and \function{proptable()} functions can be used to calculate
counts, percentages and proportions, respectively for a categorical variable.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{xtabs}\hlkeyword{(}\hlkeyword{\urltilda{}}\hlsymbol{homeless}\hlkeyword{,}{\ }\hlsymbol{HELP}\hlkeyword{)}{\ }{\ }\hlcomment{\usebox{\hlnormalsizeboxhash}{\ }display{\ }table{\ }using{\ }counts}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
homeless
homeless   housed 
     209      244 
\end{verbatim}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{perctable}\hlkeyword{(}\hlsymbol{HELP}\hlkeyword{\usebox{\hlnormalsizeboxdollar}}\hlsymbol{homeless}\hlkeyword{)}{\ }{\ }\hlcomment{\usebox{\hlnormalsizeboxhash}{\ }display{\ }table{\ }using{\ }percentages}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}

homeless   housed 
    46.1     53.9 
\end{verbatim}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{proptable}\hlkeyword{(}\hlsymbol{HELP}\hlkeyword{\usebox{\hlnormalsizeboxdollar}}\hlsymbol{homeless}\hlkeyword{)}{\ }{\ }\hlcomment{\usebox{\hlnormalsizeboxhash}{\ }display{\ }table{\ }using{\ }proportions}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}

homeless   housed 
   0.461    0.539 
\end{verbatim}
\end{kframe}}
\end{knitrout}

\authNote{NH: how best to add row and/or column totals?  rjp:  Seems like someone must
have done this already, but I don't know of a function to do it.  I've thought about writing one.  NH: would "addmargins()" be helpful?}

\subsection{The Binomial Test}

An exact confidence interval for a proportion (as well as a test of the null 
hypothesis is equal to a particular value [by default 0.5]) can be calculated
using the \function{binom.test()} function.
The standard \function{binom.test()} requires us to tabulate.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{binom.test}\hlkeyword{(}\hlnumber{209}\hlkeyword{,}{\ }\hlnumber{209}{\ }\hlkeyword{+}{\ }\hlnumber{244}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}

	Exact binomial test

data:  209 and 209 + 244 
number of successes = 209, number of trials = 453, p-value = 0.1101
alternative hypothesis: true probability of success is not equal to 0.5 
95 percent confidence interval:
 0.415 0.509 
sample estimates:
probability of success 
                 0.461 

\end{verbatim}
\end{kframe}}
\end{knitrout}

The \pkg{mosaic} package provides a formula interface that avoids the need to pre-tally
the data.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{result}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlfunctioncall{binom.test}\hlkeyword{(}\hlkeyword{\urltilda{}}\hlsymbol{homeless}{\ }=={\ }\hlstring{"{}homeless"{}}\hlkeyword{,}{\ }\hlsymbol{HELP}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlsymbol{result}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}

	Exact binomial test

data:  HELP$homeless == "homeless" 
number of successes = 209, number of trials = 453, p-value = 0.1101
alternative hypothesis: true probability of success is not equal to 0.5 
95 percent confidence interval:
 0.415 0.509 
sample estimates:
probability of success 
                 0.461 

\end{verbatim}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{names}\hlkeyword{(}\hlsymbol{result}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
[1] "statistic"   "parameter"   "p.value"     "conf.int"    "estimate"    "null.value" 
[7] "alternative" "method"      "data.name"  
\end{verbatim}
\end{kframe}}
\end{knitrout}


As is generally the case with commands of this sort, 
there are a number of useful quantities available from 
the object returned by the function.  
For example, the user can extract the confidence interval either manually
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{result}\hlkeyword{\usebox{\hlnormalsizeboxdollar}}\hlsymbol{conf.int}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
[1] 0.415 0.509
attr(,"conf.level")
[1] 0.95
\end{verbatim}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{result}\hlkeyword{\usebox{\hlnormalsizeboxdollar}}\hlsymbol{conf.int}\hlkeyword{[}\hlnumber{1}\hlkeyword{]}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
[1] 0.415
\end{verbatim}
\end{kframe}}
\end{knitrout}

or via the \function{interval()} function in the \pkg{mosaic} package.%
\footnote{A word of explanation is in order here.  In \R\ what you see is not 
what you get.  Most of the objects we encounter in \R\ have a \function{print()}
method.  So when we get \code{result}, what we are seeing displayed is
\code{print(result)}.  There may be a good deal of additional information
lurking inside the object itself.  To make matter even more complicated, some
objects are returned \emph{invisibly}, so nothing prints.  You can still assign
the returned object to a variable and process it later, even if nothing shows up
on the screen.  This is the case for the \pkg{lattice} graphics functions, for example.
You can save a plot into a variable, say \code{myplot} and display the plot again later 
using \code{print(myplot)}.}%
\InstructorNote{You may want to read the footnote that describes what's going on here in 
a bit more detail.}%
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{interval}\hlkeyword{(}\hlsymbol{result}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
probability of success                  lower                  upper 
                 0.461                  0.415                  0.509 
\end{verbatim}
\end{kframe}}
\end{knitrout}

We can extract the p-value similarly.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{pval}\hlkeyword{(}\hlsymbol{result}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
p.value 
   0.11 
\end{verbatim}
\end{kframe}}
\end{knitrout}



\subsection{The Proportion Test}

A similar interval and test can be calculated using \function{prop.test()}.
This takes a table (as generated by \function{xtabs()} as an argument).  
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{prop.test}\hlkeyword{(}\hlfunctioncall{xtabs}\hlkeyword{(}\hlkeyword{\urltilda{}}\hlsymbol{homeless}{\ }=={\ }\hlstring{"{}housed"{}}\hlkeyword{,}{\ }\hlsymbol{HELP}\hlkeyword{)}\hlkeyword{,}{\ }\hlargument{correct}{\ }\hlargument{=}{\ }\hlnumber{FALSE}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}

	1-sample proportions test without continuity correction

data:  x, null probability 0.5 
X-squared = 2.7, df = 1, p-value = 0.1001
alternative hypothesis: true p is not equal to 0.5 
95 percent confidence interval:
 0.416 0.507 
sample estimates:
    p 
0.461 

\end{verbatim}
\end{kframe}}
\end{knitrout}

It also accepts summarized data, the way \function{binom.test()} does.
\InstructorNote{\function{prop.test()} uses a Chi-squared statistic.
Most introductory texts use a $z$-statistic.  They are equivalent, but
you may need to address this with your students.}%
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{prop.test}\hlkeyword{(}\hlnumber{209}\hlkeyword{,}{\ }\hlnumber{209}{\ }\hlkeyword{+}{\ }\hlnumber{244}\hlkeyword{,}{\ }\hlargument{correct}{\ }\hlargument{=}{\ }\hlnumber{FALSE}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}

	1-sample proportions test without continuity correction

data:  209 and 209 + 244 
X-squared = 2.7, df = 1, p-value = 0.1001
alternative hypothesis: true p is not equal to 0.5 
95 percent confidence interval:
 0.416 0.507 
sample estimates:
    p 
0.461 

\end{verbatim}
\end{kframe}}
\end{knitrout}

or counts of successes and failures as a single vector.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{prop.test}\hlkeyword{(}\hlfunctioncall{c}\hlkeyword{(}\hlnumber{209}\hlkeyword{,}{\ }\hlnumber{244}\hlkeyword{)}\hlkeyword{,}{\ }\hlargument{correct}{\ }\hlargument{=}{\ }\hlnumber{FALSE}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}

	1-sample proportions test without continuity correction

data:  c(209, 244) 
X-squared = 2.7, df = 1, p-value = 0.1001
alternative hypothesis: true p is not equal to 0.5 
95 percent confidence interval:
 0.416 0.507 
sample estimates:
    p 
0.461 

\end{verbatim}
\end{kframe}}
\end{knitrout}

To make things simpler still, we've added a formula interface in the \pkg{mosaic} package.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{prop.test}\hlkeyword{(}\hlkeyword{\urltilda{}}\hlsymbol{homeless}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}

	1-sample proportions test with continuity correction

data:  HELP$homeless 
X-squared = 2.55, df = 1, p-value = 0.1102
alternative hypothesis: true p is not equal to 0.5 
95 percent confidence interval:
 0.415 0.509 
sample estimates:
    p 
0.461 

\end{verbatim}
\end{kframe}}
\end{knitrout}


\subsection{Goodness of Fit Tests}

A variety of goodness of fit tests can be calculated against a reference 
distribution.  For the HELP data, we could test the null hypothesis that the 
proportion of subjects back in the original population in each of the 
substance abuse groups were equal.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{substab}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlfunctioncall{xtabs}\hlkeyword{(}\hlkeyword{\urltilda{}}\hlsymbol{substance}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlsymbol{substab}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
substance
alcohol cocaine  heroin 
    177     152     124 
\end{verbatim}
\end{kframe}}
\end{knitrout}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{perctable}\hlkeyword{(}\hlsymbol{HELP}\hlkeyword{\usebox{\hlnormalsizeboxdollar}}\hlsymbol{substance}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}

alcohol cocaine  heroin 
   39.1    33.6    27.4 
\end{verbatim}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{p}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlfunctioncall{c}\hlkeyword{(}\hlnumber{1}\hlkeyword{/}\hlnumber{3}\hlkeyword{,}{\ }\hlnumber{1}\hlkeyword{/}\hlnumber{3}\hlkeyword{,}{\ }\hlnumber{1}\hlkeyword{/}\hlnumber{3}\hlkeyword{)}{\ }{\ }\hlcomment{\usebox{\hlnormalsizeboxhash}{\ }equivalent{\ }to{\ }rep(1/3,{\ }3)}\hspace*{\fill}\\
\hlstd{}\hlfunctioncall{chisq.test}\hlkeyword{(}\hlsymbol{substab}\hlkeyword{,}{\ }\hlargument{p}{\ }\hlargument{=}{\ }\hlsymbol{p}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}

	Chi-squared test for given probabilities

data:  substab 
X-squared = 9.31, df = 2, p-value = 0.009508

\end{verbatim}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{total}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlfunctioncall{sum}\hlkeyword{(}\hlsymbol{substab}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlsymbol{total}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
[1] 453
\end{verbatim}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{total}{\ }\hlkeyword{*}{\ }\hlsymbol{p}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
[1] 151 151 151
\end{verbatim}
\end{kframe}}
\end{knitrout}


We can also calculate this quantity manually, in terms of observed and expected values.

\InstructorNote{We don't encourage much manual calculations in our courses}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{chisq}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlfunctioncall{sum}\hlkeyword{(}\hlkeyword{(}\hlsymbol{substab}{\ }\hlkeyword{-}{\ }\hlsymbol{total}{\ }\hlkeyword{*}{\ }\hlsymbol{p}\hlkeyword{)}\hlkeyword{\usebox{\hlnormalsizeboxhat}}\hlnumber{2}\hlkeyword{/}\hlkeyword{(}\hlsymbol{total}{\ }\hlkeyword{*}{\ }\hlsymbol{p}\hlkeyword{)}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlsymbol{chisq}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
[1] 9.31
\end{verbatim}
\begin{flushleft}
\ttfamily\noindent
\hlnumber{1}{\ }\hlkeyword{-}{\ }\hlfunctioncall{pchisq}\hlkeyword{(}\hlsymbol{chisq}\hlkeyword{,}{\ }\hlnumber{2}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
[1] 0.00951
\end{verbatim}
\end{kframe}}
\end{knitrout}


Alternatively, the \pkg{mosaic} package provides a version of \function{chisq.test()} with
more verbose output.
\FoodForThought{\code{x} is for eXtra.}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{xchisq.test}\hlkeyword{(}\hlsymbol{substab}\hlkeyword{,}{\ }\hlargument{p}{\ }\hlargument{=}{\ }\hlsymbol{p}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}

	Chi-squared test for given probabilities

data:  substab 
X-squared = 9.31, df = 2, p-value = 0.009508

 177.00   152.00   124.00 
(151.00) (151.00) (151.00)
[4.4768] [0.0066] [4.8278]
< 2.116> < 0.081> <-2.197>
     
key:
	observed
	(expected)
	[contribution to X-squared]
	<residual>
\end{verbatim}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{rm}\hlkeyword{(}\hlsymbol{substab}\hlkeyword{,}{\ }\hlsymbol{p}\hlkeyword{,}{\ }\hlsymbol{total}\hlkeyword{,}{\ }\hlsymbol{chisq}\hlkeyword{)}{\ }{\ }\hlcomment{\usebox{\hlnormalsizeboxhash}{\ }disposing{\ }of{\ }variables{\ }no{\ }longer{\ }needed.}\mbox{}
\normalfont
\end{flushleft}
\end{kframe}}
\end{knitrout}



\section{Two Quantitative Variables}

\subsection{Scatterplots}

We always encourage students to start any analysis by graphing their data.  
Here we augment a scatterplot
of the CESD (depressive symptoms) and the MCS (mental component score from the SF-36)
with a lowess (locally weighted scatterplot smoother) line.  

\InstructorNote{The lowess line can help to assess linearity of a relationship}
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{xyplot}\hlkeyword{(}\hlsymbol{cesd}{\ }\hlkeyword{\urltilda{}}{\ }\hlsymbol{mcs}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{,}{\ }\hlargument{type}{\ }\hlargument{=}{\ }\hlfunctioncall{c}\hlkeyword{(}\hlstring{"{}p"{}}\hlkeyword{,}{\ }\hlstring{"{}smooth"{}}\hlkeyword{)}\hlkeyword{,}{\ }\hlargument{pch}{\ }\hlargument{=}{\ }\hlnumber{1}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}


\centering{}\includegraphics{figures/fig-HELP-xyplot} 

\end{kframe}}
\end{knitrout}

\end{center}

For multivariate data sets, \function{splom()} will generate pairwise
scatterplots for selected variables.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{splom}\hlkeyword{(}\hlsymbol{HELP}\hlkeyword{[}\hlkeyword{,}{\ }\hlfunctioncall{c}\hlkeyword{(}\hlstring{"{}age"{}}\hlkeyword{,}{\ }\hlstring{"{}cesd"{}}\hlkeyword{,}{\ }\hlstring{"{}d1"{}}\hlkeyword{)}\hlkeyword{]}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}


\centering{}\includegraphics{figures/fig-HELP-splom} 

\end{kframe}}
\end{knitrout}



\subsection{Correlation}

Correlations can be calculated for a pair of variables, or for a matrix of variables.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{with}\hlkeyword{(}\hlsymbol{HELP}\hlkeyword{,}{\ }\hlfunctioncall{cor}\hlkeyword{(}\hlsymbol{cesd}\hlkeyword{,}{\ }\hlsymbol{mcs}\hlkeyword{)}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
[1] -0.682
\end{verbatim}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{with}\hlkeyword{(}\hlsymbol{HELP}\hlkeyword{,}{\ }\hlfunctioncall{cor}\hlkeyword{(}\hlfunctioncall{cbind}\hlkeyword{(}\hlsymbol{cesd}\hlkeyword{,}{\ }\hlsymbol{mcs}\hlkeyword{,}{\ }\hlsymbol{pcs}\hlkeyword{)}\hlkeyword{)}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
       cesd    mcs    pcs
cesd  1.000 -0.682 -0.293
mcs  -0.682  1.000  0.110
pcs  -0.293  0.110  1.000
\end{verbatim}
\end{kframe}}
\end{knitrout}


By default, Pearson correlations are provided, other variants can be specified using the
\option{method} option.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{with}\hlkeyword{(}\hlsymbol{HELP}\hlkeyword{,}{\ }\hlfunctioncall{cor}\hlkeyword{(}\hlsymbol{cesd}\hlkeyword{,}{\ }\hlsymbol{mcs}\hlkeyword{)}\hlkeyword{,}{\ }\hlargument{method}{\ }\hlargument{=}{\ }\hlstring{"{}spearman"{}}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
[1] -0.682
\end{verbatim}
\end{kframe}}
\end{knitrout}


\subsection{Simple Linear Regression}

\InstructorNote{As mentioned earlier, we tend to introduce linear regression
early in our courses.}

Linear regression models were introduced previously in 
section \ref{sec:lm}.  These use the same formula interface to specify the outcome 
and predictors.  Here we consider fitting the model \model{\VN{cesd}}{\VN{mcs}}.


\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{model}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlfunctioncall{lm}\hlkeyword{(}\hlsymbol{cesd}{\ }\hlkeyword{\urltilda{}}{\ }\hlsymbol{mcs}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlfunctioncall{coef}\hlkeyword{(}\hlsymbol{model}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
(Intercept)         mcs 
     53.902      -0.665 
\end{verbatim}
\end{kframe}}
\end{knitrout}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{summary}\hlkeyword{(}\hlsymbol{model}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}

Call:
lm(formula = cesd ~ mcs, data = HELP)

Residuals:
    Min      1Q  Median      3Q     Max 
-27.359  -6.728  -0.002   6.237  24.424 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  53.9022     1.1472    47.0   <2e-16 ***
mcs          -0.6647     0.0336   -19.8   <2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

Residual standard error: 9.16 on 451 degrees of freedom
Multiple R-squared: 0.465,	Adjusted R-squared: 0.464 
F-statistic:  392 on 1 and 451 DF,  p-value: <2e-16 

\end{verbatim}
\end{kframe}}
\end{knitrout}



\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{class}\hlkeyword{(}\hlsymbol{model}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
[1] "lm"
\end{verbatim}
\end{kframe}}
\end{knitrout}

The return value from \function{lm()} is a linear model object;
A number of functions can operate on these objects, as
seen previously with \function{coef()}.  As an additional example,
there is a function called \function{residuals()} that will return a
vector of the residuals.
\FoodForThought{\function{residuals()} can be abbreviated 
\function{resid()}.}
\InstructorNote{Another useful function is \function{predict()} }

\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{xhistogram}\hlkeyword{(}\hlkeyword{\urltilda{}}\hlfunctioncall{residuals}\hlkeyword{(}\hlsymbol{model}\hlkeyword{)}\hlkeyword{,}{\ }\hlargument{density}{\ }\hlargument{=}{\ }\hlnumber{TRUE}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}


\centering{}\includegraphics{figures/fig-lmhist} 

\end{kframe}}
\end{knitrout}

\end{center}
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{qqmath}\hlkeyword{(}\hlkeyword{\urltilda{}}\hlfunctioncall{resid}\hlkeyword{(}\hlsymbol{model}\hlkeyword{)}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}


\centering{}\includegraphics{figures/fig-HELP-resid-qq} 

\end{kframe}}
\end{knitrout}

\end{center}
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{xyplot}\hlkeyword{(}\hlfunctioncall{resid}\hlkeyword{(}\hlsymbol{model}\hlkeyword{)}{\ }\hlkeyword{\urltilda{}}{\ }\hlfunctioncall{fitted}\hlkeyword{(}\hlsymbol{model}\hlkeyword{)}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}


\centering{}\includegraphics{figures/fig-HELP-resid-plot} 

\end{kframe}}
\end{knitrout}

\end{center}


In addition, the \function{plot()} method can produce a number of diagnostic plots
(see \texttt{?plot.lm}).

\begin{multicols}{2}
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{plot}\hlkeyword{(}\hlsymbol{model}\hlkeyword{,}{\ }\hlargument{which}{\ }\hlargument{=}{\ }\hlnumber{1}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}


\centering{}\includegraphics{figures/fig-HELP-lmplot1} 

\end{kframe}}
\end{knitrout}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{plot}\hlkeyword{(}\hlsymbol{model}\hlkeyword{,}{\ }\hlargument{which}{\ }\hlargument{=}{\ }\hlnumber{2}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}


\centering{}\includegraphics{figures/fig-HELP-lmplot2} 

\end{kframe}}
\end{knitrout}

\end{center}
\end{multicols}

\begin{problem}
Using the HELP dataset, fit a simple linear regression model 
predicting the number of drinks per day as a function of the mental
component score.  

This model can be specified using the formula:
\model{\VN{i1}}{\VN{mcs}}.  

Assess the distribution of the residuals for this model.
\end{problem}


\section{Two Categorical Variables}


\subsection{Cross classification Tables}

Cross classification (two-way or $R$ by $C$) tables can be constructed for
two (or more) categorical variables.  Here we consider the contingency table
for homeless status (homeless one or more nights in the past 6 months or housed) 
and sex.

\subsubsection{From Raw Data}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{xtabs}\hlkeyword{(}\hlkeyword{\urltilda{}}\hlsymbol{homeless}{\ }\hlkeyword{+}{\ }\hlsymbol{sex}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
          sex
homeless   female male
  homeless     40  169
  housed       67  177
\end{verbatim}
\end{kframe}}
\end{knitrout}


\subsubsection{Building Cross Tables from Already Summarized Data}

\authNote{Need to decide how we want to do this.}

\subsubsection{Epidemiologic statistics}
\label{sec:epistats}

To demonstrate how to extend \R\ using your own functions, we can write
one which calculates epidemiologic statistics such as the odds ratio (OR).
More information about writing your own functions can be found in 
section
\ref{sec:writingFunctions}.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{odds.ratio}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlkeyword{function}\hlkeyword{(}\hlformalargs{x}\hlkeyword{,}{\ }\hlformalargs{y}\hlkeyword{,}{\ }\hlformalargs{ds}\hlkeyword{)}{\ }\hlkeyword{\usebox{\hlnormalsizeboxopenbrace}}\hspace*{\fill}\\
\hlstd{}{\ }{\ }{\ }{\ }\hlsymbol{tab}{\ }\hlassignement{=}{\ }\hlfunctioncall{xtabs}\hlkeyword{(}\hlkeyword{\urltilda{}}\hlsymbol{x}{\ }\hlkeyword{+}{\ }\hlsymbol{y}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}{\ }{\ }{\ }{\ }\hlfunctioncall{return}\hlkeyword{(}\hlsymbol{tab}\hlkeyword{[}\hlnumber{1}\hlkeyword{,}{\ }\hlnumber{1}\hlkeyword{]}{\ }\hlkeyword{*}{\ }\hlsymbol{tab}\hlkeyword{[}\hlnumber{2}\hlkeyword{,}{\ }\hlnumber{2}\hlkeyword{]}\hlkeyword{/}\hlkeyword{(}\hlsymbol{tab}\hlkeyword{[}\hlnumber{1}\hlkeyword{,}{\ }\hlnumber{2}\hlkeyword{]}{\ }\hlkeyword{*}{\ }\hlsymbol{tab}\hlkeyword{[}\hlnumber{2}\hlkeyword{,}{\ }\hlnumber{1}\hlkeyword{]}\hlkeyword{)}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlkeyword{\usebox{\hlnormalsizeboxclosebrace}}\hspace*{\fill}\\
\hlstd{}\hlfunctioncall{with}\hlkeyword{(}\hlsymbol{HELP}\hlkeyword{,}{\ }\hlfunctioncall{odds.ratio}\hlkeyword{(}\hlsymbol{homeless}\hlkeyword{,}{\ }\hlsymbol{sex}\hlkeyword{)}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
[1] 0.625
\end{verbatim}
\end{kframe}}
\end{knitrout}


\authNote{NH to expand}

\subsubsection{Graphical Summaries}

Graphical summaries of cross classification tables may be helpful in visualizing
associations.  Mosaic plots are one example (though the jury is still out
regarding its utility, relative to the low data to ink ratio \cite{Tufte:2001:Visual}.  
Here we see that males tend to be over-represented
amongst the homeless subjects (as represented by the horizontal line which is higher for
the homeless rather than the housed).  
\FoodForThought{The \function{mosaic()} function 
in the \pkg{vcd} package also makes mosaic plots.}

\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{mosaicplot}\hlkeyword{(}\hlfunctioncall{xtabs}\hlkeyword{(}\hlkeyword{\urltilda{}}\hlsymbol{homeless}{\ }\hlkeyword{+}{\ }\hlsymbol{sex}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{)}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}


\centering{}\includegraphics{figures/fig-mosaicplot} 

\end{kframe}}
\end{knitrout}

\end{center}

\subsection{Chi-squared tests}

%with(HELP, chisq.test(homeless, sex, correct=FALSE))
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{chisq.test}\hlkeyword{(}\hlfunctioncall{xtabs}\hlkeyword{(}\hlkeyword{\urltilda{}}\hlsymbol{homeless}{\ }\hlkeyword{+}{\ }\hlsymbol{sex}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{)}\hlkeyword{,}{\ }\hlargument{correct}{\ }\hlargument{=}{\ }\hlnumber{FALSE}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}

	Pearson's Chi-squared test

data:  xtabs(~homeless + sex, data = HELP) 
X-squared = 4.32, df = 1, p-value = 0.03767

\end{verbatim}
\end{kframe}}
\end{knitrout}


There is a statistically significant association found: it is unlikely that we would observe
an association this strong if there was homeless status and sex were independent back in the 
population.

\subsubsection{Displaying additional information}

When a student finds a significant association, 
it's important for them to be able to interpret this in the context of the problem. 
The \function{xchisq.test()} function provides additional details to help with this process.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{xchisq.test}\hlkeyword{(}\hlfunctioncall{xtabs}\hlkeyword{(}\hlkeyword{\urltilda{}}\hlsymbol{homeless}{\ }\hlkeyword{+}{\ }\hlsymbol{sex}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{)}\hlkeyword{,}{\ }\hlargument{correct}{\ }\hlargument{=}{\ }\hlnumber{FALSE}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}

	Pearson's Chi-squared test

data:  xtabs(~homeless + sex, data = HELP) 
X-squared = 4.32, df = 1, p-value = 0.03767

  40.00   169.00 
( 49.37) (159.63)
 [1.78]   [0.55] 
<-1.33>  < 0.74> 
   
  67.00   177.00 
( 57.63) (186.37)
 [1.52]   [0.47] 
< 1.23>  <-0.69> 
   
key:
	observed
	(expected)
	[contribution to X-squared]
	<residual>
\end{verbatim}
\end{kframe}}
\end{knitrout}


We observe that there are fewer homeless women, and more homeless men that would be expected.

\subsection{Fisher's Exact Test}

An exact test can also be calculated.  This is fairly computationally straightforward for 2 by 2
tables.  Options to help constrain the size of the problem for larger tables exist
(see \verb!?fisher.test()!).

%with(HELP, fisher.test(homeless, sex))
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{fisher.test}\hlkeyword{(}\hlfunctioncall{xtabs}\hlkeyword{(}\hlkeyword{\urltilda{}}\hlsymbol{homeless}{\ }\hlkeyword{+}{\ }\hlsymbol{sex}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{)}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}

	Fisher's Exact Test for Count Data

data:  xtabs(~homeless + sex, data = HELP) 
p-value = 0.0456
alternative hypothesis: true odds ratio is not equal to 1 
95 percent confidence interval:
 0.389 0.997 
sample estimates:
odds ratio 
     0.626 

\end{verbatim}
\end{kframe}}
\end{knitrout}


\section{Quantitative Response to a Categorical Predictor}

\subsection{A Bivariate Predictor: Numerical and Graphical Summaries}
Here we will compare the distributions of CESD scores by sex.

The \function{aggregate()} function can be used to calculate the mean CESD score
for each of the two groups 
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{aggregate}\hlkeyword{(}\hlsymbol{cesd}{\ }\hlkeyword{\urltilda{}}{\ }\hlsymbol{sex}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{,}{\ }\hlargument{FUN}{\ }\hlargument{=}{\ }\hlsymbol{mean}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
     sex cesd
1 female 36.9
2   male 31.6
\end{verbatim}
\end{kframe}}
\end{knitrout}


The \function{summary()} function can provide more statistics by group.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{summary}\hlkeyword{(}\hlsymbol{cesd}{\ }\hlkeyword{\urltilda{}}{\ }\hlsymbol{sex}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{,}{\ }\hlargument{fun}{\ }\hlargument{=}{\ }\hlsymbol{favstats}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
cesd    N=453

+-------+------+---+--+---+----+----+----+----+----+---+
|       |      |N  |0%|25%|50% |75% |100%|mean|sd  |var|
+-------+------+---+--+---+----+----+----+----+----+---+
|sex    |female|107|3 |29 |38.0|46.5|60  |36.9|13.0|169|
|       |male  |346|1 |24 |32.5|40.0|58  |31.6|12.1|146|
+-------+------+---+--+---+----+----+----+----+----+---+
|Overall|      |453|1 |25 |34.0|41.0|60  |32.8|12.5|157|
+-------+------+---+--+---+----+----+----+----+----+---+
\end{verbatim}
\end{kframe}}
\end{knitrout}



Boxplots are a particularly helpful graphical display to compare distributions.
The \function{bwplot()} function can be used to display the boxplots for the
CESD scores separately by sex.  We see from both the numerical and graphical
displays that women tend to have slightly higher CESD scores than men.

\FoodForThought{Although we usually put explanatory variables along the horizontal axis,
page layout sometimes makes the other orientation preferable for these plots.}
%\vspace{-8mm}
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{bwplot}\hlkeyword{(}\hlsymbol{sex}{\ }\hlkeyword{\urltilda{}}{\ }\hlsymbol{cesd}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}


\centering{}\includegraphics{figures/fig-cesd-box} 

\end{kframe}}
\end{knitrout}

\end{center}

When sample sizes are small, there is no reason to summarize with a boxplot
since  \function{xyplot()} can handle categorical predictors.
Even with 10--20 observations in a group, a scatter plot is often quite readable.
Setting the alpha level helps detect multiple observations with the same value.
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{xyplot}\hlkeyword{(}\hlsymbol{sex}{\ }\hlkeyword{\urltilda{}}{\ }\hlsymbol{length}\hlkeyword{,}{\ }\hlsymbol{KidsFeet}\hlkeyword{,}{\ }\hlargument{alpha}{\ }\hlargument{=}{\ }\hlnumber{0.6}\hlkeyword{,}{\ }\hlargument{cex}{\ }\hlargument{=}{\ }\hlnumber{1.4}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}


\centering{}\includegraphics{figures/fig-KidsFeet-xy} 

\end{kframe}}
\end{knitrout}

\end{center}
\FoodForThought{One of us once saw a biologist proudly present
side-by-side boxplots.  Thinking a major victory had been won, he naively
asked how many observations were in each group.  ``Four,'' replied the 
biologist.}

\subsection{A Bivariate Predictor: Two-sample t}

The Student's two sample t-test can be run without or with an equal variance assumption.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{t.test}\hlkeyword{(}\hlsymbol{cesd}{\ }\hlkeyword{\urltilda{}}{\ }\hlsymbol{sex}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{,}{\ }\hlargument{var.equal}{\ }\hlargument{=}{\ }\hlnumber{FALSE}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}

	Welch Two Sample t-test

data:  cesd by sex 
t = 3.73, df = 167, p-value = 0.0002587
alternative hypothesis: true difference in means is not equal to 0 
95 percent confidence interval:
 2.49 8.09 
sample estimates:
mean in group female   mean in group male 
                36.9                 31.6 

\end{verbatim}
\end{kframe}}
\end{knitrout}


We see that there is a statistically significant difference between the two groups.


\subsection{Non-parametric 2 group tests}

The same conclusion is seen using a non-parametric (Wilcoxon rank sum) test.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{wilcox.test}\hlkeyword{(}\hlsymbol{cesd}{\ }\hlkeyword{\urltilda{}}{\ }\hlsymbol{sex}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}

	Wilcoxon rank sum test with continuity correction

data:  cesd by sex 
W = 23105, p-value = 0.0001033
alternative hypothesis: true location shift is not equal to 0 

\end{verbatim}
\end{kframe}}
\end{knitrout}



\subsection{Permutation test}

Here we extend the methods introduced in section \ref{sec:comparing-two-means} to 
undertake a two-sided test.

%rtest.stats[simulations+1,] <- test.stat  # add in the observed value
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{simulations}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlnumber{500}\hspace*{\fill}\\
\hlstd{}\hlsymbol{test.stat}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlfunctioncall{abs}\hlkeyword{(}\hlfunctioncall{diff}\hlkeyword{(}\hlfunctioncall{aggregate}\hlkeyword{(}\hlsymbol{cesd}{\ }\hlkeyword{\urltilda{}}{\ }\hlsymbol{sex}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{,}{\ }\hlsymbol{mean}\hlkeyword{)}\hlkeyword{\usebox{\hlnormalsizeboxdollar}}\hlsymbol{cesd}\hlkeyword{)}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlsymbol{test.stat}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
[1] 5.29
\end{verbatim}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{rtest.stats}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlfunctioncall{do}\hlkeyword{(}\hlsymbol{simulations}\hlkeyword{)}{\ }\hlkeyword{*}{\ }\hlfunctioncall{c}\hlkeyword{(}\hlargument{diff}{\ }\hlargument{=}{\ }\hlfunctioncall{diff}\hlkeyword{(}\hlfunctioncall{aggregate}\hlkeyword{(}\hlsymbol{cesd}{\ }\hlkeyword{\urltilda{}}{\ }\hlfunctioncall{shuffle}\hlkeyword{(}\hlsymbol{sex}\hlkeyword{)}\hlkeyword{,}\hspace*{\fill}\\
\hlstd{}{\ }{\ }{\ }{\ }\hlsymbol{HELP}\hlkeyword{,}{\ }\hlsymbol{mean}\hlkeyword{)}\hlkeyword{\usebox{\hlnormalsizeboxdollar}}\hlsymbol{cesd}\hlkeyword{)}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlfunctioncall{histogram}\hlkeyword{(}\hlkeyword{\urltilda{}}\hlfunctioncall{abs}\hlkeyword{(}\hlsymbol{diff}\hlkeyword{)}\hlkeyword{,}{\ }\hlsymbol{rtest.stats}\hlkeyword{,}{\ }\hlargument{n}{\ }\hlargument{=}{\ }\hlnumber{40}\hlkeyword{,}{\ }\hlargument{xlim}{\ }\hlargument{=}{\ }\hlfunctioncall{c}\hlkeyword{(}\hlnumber{0}\hlkeyword{,}{\ }\hlnumber{6}\hlkeyword{)}\hlkeyword{,}{\ }\hlargument{groups}{\ }\hlargument{=}{\ }\hlfunctioncall{abs}\hlkeyword{(}\hlsymbol{rtest.stats}\hlkeyword{\usebox{\hlnormalsizeboxdollar}}\hlsymbol{diff}\hlkeyword{)}{\ }\hlkeyword{\usebox{\hlnormalsizeboxgreaterthan}=}\hspace*{\fill}\\
\hlstd{}{\ }{\ }{\ }{\ }\hlsymbol{test.stat}\hlkeyword{,}{\ }\hlargument{pch}{\ }\hlargument{=}{\ }\hlnumber{16}\hlkeyword{,}{\ }\hlargument{cex}{\ }\hlargument{=}{\ }\hlnumber{0.8}\hlkeyword{)}{\ }{\ }\hlcomment{\usebox{\hlnormalsizeboxhash}{\ }was{\ }dotPlot}\hspace*{\fill}\\
\hlstd{}\hlfunctioncall{ladd}\hlkeyword{(}\hlfunctioncall{panel.abline}\hlkeyword{(}\hlargument{v}{\ }\hlargument{=}{\ }\hlsymbol{test.stat}\hlkeyword{)}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}


\centering{}\includegraphics{figures/fig-permute-HELP} 

\end{kframe}}
\end{knitrout}



\authNote{NH: line still isn't showing up}

The same conclusion is observed with a permutation test (the
observed value is nowhere in the vicinity of the permuted values).

\subsection{One-way ANOVA}

Earlier comparisons were between two groups: we can also consider testing differences 
in CESD scores by primary substance of abuse (heroin, cocaine, or alcohol).

\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{bwplot}\hlkeyword{(}\hlsymbol{cesd}{\ }\hlkeyword{\urltilda{}}{\ }\hlsymbol{substance}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}


\centering{}\includegraphics{figures/fig-cesd-oneway} 

\end{kframe}}
\end{knitrout}

\end{center}


\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{aggregate}\hlkeyword{(}\hlsymbol{cesd}{\ }\hlkeyword{\urltilda{}}{\ }\hlsymbol{substance}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{,}{\ }\hlargument{FUN}{\ }\hlargument{=}{\ }\hlsymbol{mean}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
  substance cesd
1   alcohol 34.4
2   cocaine 29.4
3    heroin 34.9
\end{verbatim}
\end{kframe}}
\end{knitrout}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{mod}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlfunctioncall{aov}\hlkeyword{(}\hlsymbol{cesd}{\ }\hlkeyword{\urltilda{}}{\ }\hlsymbol{substance}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlfunctioncall{summary}\hlkeyword{(}\hlsymbol{mod}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
             Df Sum Sq Mean Sq F value  Pr(>F)    
substance     2   2704    1352    8.94 0.00016 ***
Residuals   450  68084     151                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 
\end{verbatim}
\end{kframe}}
\end{knitrout}

While still high (scores of 16 or more are generally considered to be 
``severe'' symptoms), the cocaine-involved group tend to have lower 
scores than those whose primary substances are alcohol or heroin.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{mod1}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlfunctioncall{lm}\hlkeyword{(}\hlsymbol{cesd}{\ }\hlkeyword{\urltilda{}}{\ }\hlnumber{1}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlsymbol{mod2}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlfunctioncall{lm}\hlkeyword{(}\hlsymbol{cesd}{\ }\hlkeyword{\urltilda{}}{\ }\hlsymbol{substance}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\end{kframe}}
\end{knitrout}


The \function{anova()} command can be used to formally 
compare two (nested) models.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{anova}\hlkeyword{(}\hlsymbol{mod1}\hlkeyword{,}{\ }\hlsymbol{mod2}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
Analysis of Variance Table

Model 1: cesd ~ 1
Model 2: cesd ~ substance
  Res.Df   RSS Df Sum of Sq    F  Pr(>F)    
1    452 70788                              
2    450 68084  2      2704 8.94 0.00016 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 
\end{verbatim}
\end{kframe}}
\end{knitrout}



\subsection{Tukey's Honest Significant Differences}

There are a variety of multiple comparison procedures that can be
used after fitting an ANOVA model.  One of these is Tukey's Honest
Significant Difference (HSD).  Other options are available with the 
\pkg{multcomp} package.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{with}\hlkeyword{(}\hlsymbol{HELP}\hlkeyword{,}{\ }\hlfunctioncall{tapply}\hlkeyword{(}\hlsymbol{cesd}\hlkeyword{,}{\ }\hlsymbol{substance}\hlkeyword{,}{\ }\hlsymbol{mean}\hlkeyword{)}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
alcohol cocaine  heroin 
   34.4    29.4    34.9 
\end{verbatim}
\end{kframe}}
\end{knitrout}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{compare}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlfunctioncall{TukeyHSD}\hlkeyword{(}\hlsymbol{mod}\hlkeyword{,}{\ }\hlstring{"{}substance"{}}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlsymbol{compare}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = cesd ~ substance, data = HELP)

$substance
                  diff   lwr   upr p adj
cocaine-alcohol -4.952 -8.15 -1.75 0.001
heroin-alcohol   0.498 -2.89  3.89 0.936
heroin-cocaine   5.450  1.95  8.95 0.001

\end{verbatim}
\end{kframe}}
\end{knitrout}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{plot}\hlkeyword{(}\hlsymbol{compare}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}


\centering{}\includegraphics{figures/fig-help-hsd3} 

\end{kframe}}
\end{knitrout}


Again, we see that the cocaine group has significantly lower CESD scores
than the other two groups.

\section{Categorical Response to a Quantitative Predictor}

\subsection{Logistic Regression}

Logistic regression is available from within the \function{glm()} function: a variety of
link functions and distributional forms for generalized linear models are supported.

\FoodForThought{\function{glm()} has arguments \option{family}  and
\option{link}.  The \code{logit} link is the default link for the binomial family,
so we don't need to specify it here.}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{logitmod}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlfunctioncall{glm}\hlkeyword{(}\hlsymbol{homeless}{\ }\hlkeyword{\urltilda{}}{\ }\hlsymbol{age}{\ }\hlkeyword{+}{\ }\hlsymbol{female}\hlkeyword{,}{\ }\hlargument{family}{\ }\hlargument{=}{\ }\hlsymbol{binomial}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlfunctioncall{summary}\hlkeyword{(}\hlsymbol{logitmod}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}

Call:
glm(formula = homeless ~ age + female, family = binomial, data = HELP)

Deviance Residuals: 
   Min      1Q  Median      3Q     Max  
-1.547  -1.202   0.918   1.123   1.360  

Coefficients:
            Estimate Std. Error z value Pr(>|z|)  
(Intercept)   0.8926     0.4537    1.97    0.049 *
age          -0.0239     0.0124   -1.92    0.055 .
female        0.4920     0.2282    2.16    0.031 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 625.28  on 452  degrees of freedom
Residual deviance: 617.19  on 450  degrees of freedom
AIC: 623.2

Number of Fisher Scoring iterations: 4

\end{verbatim}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{exp}\hlkeyword{(}\hlfunctioncall{coef}\hlkeyword{(}\hlsymbol{logitmod}\hlkeyword{)}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
(Intercept)         age      female 
      2.442       0.976       1.636 
\end{verbatim}
\end{kframe}}
\end{knitrout}


\section{Survival Time Outcomes}

Extensive support for Survival (Time to Event) analysis is available within the 
\pkg{survival} package.

\subsection{Kaplan-Meier plot}

\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{library}\hlkeyword{(}\hlsymbol{survival}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlsymbol{fit}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlfunctioncall{survfit}\hlkeyword{(}\hlfunctioncall{Surv}\hlkeyword{(}\hlsymbol{dayslink}\hlkeyword{,}{\ }\hlsymbol{linkstatus}\hlkeyword{)}{\ }\hlkeyword{\urltilda{}}{\ }\hlsymbol{treat}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlfunctioncall{plot}\hlkeyword{(}\hlsymbol{fit}\hlkeyword{,}{\ }\hlargument{conf.int}{\ }\hlargument{=}{\ }\hlnumber{FALSE}\hlkeyword{,}{\ }\hlargument{lty}{\ }\hlargument{=}{\ }\hlnumber{1}\hlkeyword{:}\hlnumber{2}\hlkeyword{,}{\ }\hlargument{lwd}{\ }\hlargument{=}{\ }\hlnumber{2}\hlkeyword{,}{\ }\hlargument{xlab}{\ }\hlargument{=}{\ }\hlstring{"{}time{\ }(in{\ }days)"{}}\hlkeyword{,}\hspace*{\fill}\\
\hlstd{}{\ }{\ }{\ }{\ }\hlargument{ylab}{\ }\hlargument{=}{\ }\hlstring{"{}P(not{\ }linked)"{}}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlfunctioncall{legend}\hlkeyword{(}\hlnumber{20}\hlkeyword{,}{\ }\hlnumber{0.4}\hlkeyword{,}{\ }\hlargument{legend}{\ }\hlargument{=}{\ }\hlfunctioncall{c}\hlkeyword{(}\hlstring{"{}Control"{}}\hlkeyword{,}{\ }\hlstring{"{}Treatment"{}}\hlkeyword{)}\hlkeyword{,}{\ }\hlargument{lty}{\ }\hlargument{=}{\ }\hlfunctioncall{c}\hlkeyword{(}\hlnumber{1}\hlkeyword{,}{\ }\hlnumber{2}\hlkeyword{)}\hlkeyword{,}\hspace*{\fill}\\
\hlstd{}{\ }{\ }{\ }{\ }\hlargument{lwd}{\ }\hlargument{=}{\ }\hlnumber{2}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlfunctioncall{title}\hlkeyword{(}\hlstring{"{}Product-Limit{\ }Survival{\ }Estimates{\ }(time{\ }to{\ }linkage)"{}}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}


\centering{}\includegraphics{figures/fig-help-km} 

\end{kframe}}
\end{knitrout}

\end{center}

We see that the subjects in the treatment (HELP clinic) were significantly more likely to 
link to primary care than the control (usual care) group.

\subsection{Cox proportional hazards model}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{library}\hlkeyword{(}\hlsymbol{survival}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlfunctioncall{summary}\hlkeyword{(}\hlfunctioncall{coxph}\hlkeyword{(}\hlfunctioncall{Surv}\hlkeyword{(}\hlsymbol{dayslink}\hlkeyword{,}{\ }\hlsymbol{linkstatus}\hlkeyword{)}{\ }\hlkeyword{\urltilda{}}{\ }\hlsymbol{age}{\ }\hlkeyword{+}{\ }\hlsymbol{substance}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{)}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
Call:
coxph(formula = Surv(dayslink, linkstatus) ~ age + substance, 
    data = HELP)

  n= 431, number of events= 163 
   (22 observations deleted due to missingness)

                     coef exp(coef) se(coef)     z Pr(>|z|)
age               0.00893   1.00897  0.01026  0.87     0.38
substancecocaine  0.18045   1.19775  0.18100  1.00     0.32
substanceheroin  -0.28970   0.74849  0.21725 -1.33     0.18

                 exp(coef) exp(-coef) lower .95 upper .95
age                  1.009      0.991     0.989      1.03
substancecocaine     1.198      0.835     0.840      1.71
substanceheroin      0.748      1.336     0.489      1.15

Concordance= 0.55  (se = 0.023 )
Rsquare= 0.014   (max possible= 0.988 )
Likelihood ratio test= 6.11  on 3 df,   p=0.106
Wald test            = 5.84  on 3 df,   p=0.12
Score (logrank) test = 5.91  on 3 df,   p=0.116

\end{verbatim}
\end{kframe}}
\end{knitrout}


Neither age, nor substance group was significantly associated with linkage to primary care.


\section{More than Two Variables}

\subsection{Two (or more) way ANOVA}

We can fit a two (or more) way ANOVA model, without or with an interaction,
using the same modeling syntax.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{bwplot}\hlkeyword{(}\hlsymbol{cesd}{\ }\hlkeyword{\urltilda{}}{\ }\hlsymbol{substance}{\ }\hlkeyword{|}{\ }\hlsymbol{sex}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}


\centering{}\includegraphics{figures/fig-help-aovplot} 

\end{kframe}}
\end{knitrout}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{summary}\hlkeyword{(}\hlfunctioncall{aov}\hlkeyword{(}\hlsymbol{cesd}{\ }\hlkeyword{\urltilda{}}{\ }\hlsymbol{substance}{\ }\hlkeyword{+}{\ }\hlsymbol{sex}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{)}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
             Df Sum Sq Mean Sq F value  Pr(>F)    
substance     2   2704    1352    9.27 0.00011 ***
sex           1   2569    2569   17.61 3.3e-05 ***
Residuals   449  65515     146                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 
\end{verbatim}
\end{kframe}}
\end{knitrout}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{summary}\hlkeyword{(}\hlfunctioncall{aov}\hlkeyword{(}\hlsymbol{cesd}{\ }\hlkeyword{\urltilda{}}{\ }\hlsymbol{substance}{\ }\hlkeyword{*}{\ }\hlsymbol{sex}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{)}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
               Df Sum Sq Mean Sq F value  Pr(>F)    
substance       2   2704    1352    9.25 0.00012 ***
sex             1   2569    2569   17.57 3.3e-05 ***
substance:sex   2    146      73    0.50 0.60752    
Residuals     447  65369     146                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 
\end{verbatim}
\end{kframe}}
\end{knitrout}

There's little evidence for the interaction, though there are statistically
significant main effects terms for \VN{substance} group and 
\VN{sex}.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{xyplot}\hlkeyword{(}\hlsymbol{cesd}{\ }\hlkeyword{\urltilda{}}{\ }\hlsymbol{substance}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{,}{\ }\hlargument{groups}{\ }\hlargument{=}{\ }\hlsymbol{sex}\hlkeyword{,}{\ }\hlargument{type}{\ }\hlargument{=}{\ }\hlstring{"{}a"{}}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}


\centering{}\includegraphics{figures/fig-help-interaction} 

\end{kframe}}
\end{knitrout}



\subsection{Multiple Regression}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{lm1}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlfunctioncall{lm}\hlkeyword{(}\hlsymbol{cesd}{\ }\hlkeyword{\urltilda{}}{\ }\hlsymbol{mcs}{\ }\hlkeyword{+}{\ }\hlsymbol{age}{\ }\hlkeyword{+}{\ }\hlsymbol{sex}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlfunctioncall{summary}\hlkeyword{(}\hlsymbol{lm1}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}

Call:
lm(formula = cesd ~ mcs + age + sex, data = HELP)

Residuals:
    Min      1Q  Median      3Q     Max 
-26.924  -6.363   0.403   6.453  25.217 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  53.8303     2.3617   22.79   <2e-16 ***
mcs          -0.6548     0.0336  -19.50   <2e-16 ***
age           0.0553     0.0556    1.00   0.3200    
sexmale      -2.8993     1.0137   -2.86   0.0044 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

Residual standard error: 9.09 on 449 degrees of freedom
Multiple R-squared: 0.476,	Adjusted R-squared: 0.473 
F-statistic:  136 on 3 and 449 DF,  p-value: <2e-16 

\end{verbatim}
\end{kframe}}
\end{knitrout}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{lm2}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlfunctioncall{lm}\hlkeyword{(}\hlsymbol{cesd}{\ }\hlkeyword{\urltilda{}}{\ }\hlsymbol{mcs}{\ }\hlkeyword{+}{\ }\hlsymbol{age}{\ }\hlkeyword{+}{\ }\hlsymbol{sex}{\ }\hlkeyword{+}{\ }\hlsymbol{mcs}{\ }\hlkeyword{*}{\ }\hlsymbol{sex}\hlkeyword{,}{\ }\hlargument{data}{\ }\hlargument{=}{\ }\hlsymbol{HELP}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlfunctioncall{summary}\hlkeyword{(}\hlsymbol{lm2}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}

Call:
lm(formula = cesd ~ mcs + age + sex + mcs * sex, data = HELP)

Residuals:
    Min      1Q  Median      3Q     Max 
-26.667  -6.406   0.289   6.133  24.832 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  55.3906     2.9903   18.52   <2e-16 ***
mcs          -0.7082     0.0712   -9.95   <2e-16 ***
age           0.0549     0.0556    0.99    0.324    
sexmale      -4.9421     2.6055   -1.90    0.058 .  
mcs:sexmale   0.0687     0.0807    0.85    0.395    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

Residual standard error: 9.09 on 448 degrees of freedom
Multiple R-squared: 0.477,	Adjusted R-squared: 0.472 
F-statistic:  102 on 4 and 448 DF,  p-value: <2e-16 

\end{verbatim}
\end{kframe}}
\end{knitrout}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{anova}\hlkeyword{(}\hlsymbol{lm1}\hlkeyword{,}{\ }\hlsymbol{lm2}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
Analysis of Variance Table

Model 1: cesd ~ mcs + age + sex
Model 2: cesd ~ mcs + age + sex + mcs * sex
  Res.Df   RSS Df Sum of Sq    F Pr(>F)
1    449 37088                         
2    448 37028  1      59.9 0.72    0.4
\end{verbatim}
\end{kframe}}
\end{knitrout}

There is little evidence for an interaction effect: we may want
to drop this from the model.



\section{Probability and Random Variables}

\label{sec:DiscreteDistributions}
\label{sec:probability}

\R\ can calculate quantities related to probability distributions of all types.  
It is straightforward to generate
random variables from these distributions, which can be used 
for simulation and analysis.

Table \ref{core:dist} displays the basenames for probability distributions 
available within base \R.  These functions can be prefixed by {\tt d} to 
find the density function for the distribution, {\tt p} to find the 
cumulative density function, {\tt q} to find quantiles, and {\tt r} to 
generate random draws. For example, to find the density function of a binomial
random variable, use the command \function{dbinom()}.
The \function{qDIST()} function is the inverse of the 
{\tt pDIST()} function, for a given basename {\tt DIST}. 

\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{pnorm}\hlkeyword{(}\hlnumber{1.96}\hlkeyword{,}{\ }\hlnumber{0}\hlkeyword{,}{\ }\hlnumber{1}\hlkeyword{)}{\ }{\ }\hlcomment{\usebox{\hlnormalsizeboxhash}{\ }P(Z{\ }\usebox{\hlnormalsizeboxlessthan}{\ }1.96)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
[1] 0.975
\end{verbatim}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{qnorm}\hlkeyword{(}\hlnumber{0.975}\hlkeyword{,}{\ }\hlnumber{0}\hlkeyword{,}{\ }\hlnumber{1}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
[1] 1.96
\end{verbatim}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{integrate}\hlkeyword{(}\hlsymbol{dnorm}\hlkeyword{,}{\ }\hlkeyword{-}\hlnumber{Inf}\hlkeyword{,}{\ }\hlnumber{0}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
0.5 with absolute error < 4.7e-05
\end{verbatim}
\end{kframe}}
\end{knitrout}



\begin{table}
\begin{center}
\caption{basename for probability distribution and random number generation}
\label{core:dist}
\begin{tabular}{|c|c|c|} \hline
Distribution   & NAME                 \\ \hline
Beta           &  {\tt beta}        \\
binomial       &  {\tt binom}    \\
Cauchy         &  {\tt cauchy}   \\
chi-square     &  {\tt chisq}    \\
exponential    &  {\tt exp}      \\
F              &  {\tt f}        \\
gamma          &  {\tt gamma}    \\
geometric      &  {\tt geom}     \\
hypergeometric &  {\tt hyper}    \\
logistic       &  {\tt logis}    \\
lognormal      &  {\tt lnorm}    \\
negative binomial &  {\tt nbinom} \\
normal         &  {\tt norm}      \\
Poisson        &  {\tt pois}      \\
Student's t    &  {\tt t}        \\
Uniform        &  {\tt unif}     \\
Weibull        &  {\tt weibull}   \\ \hline
\end{tabular}
\end{center}
\end{table}

\begin{problem}
Generate a sample of 1000 exponential random variables with rate parameter
equal to 2, and calculate the mean of those variables.
\end{problem}
\begin{solution}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{x}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlfunctioncall{rexp}\hlkeyword{(}\hlnumber{1000}\hlkeyword{,}{\ }\hlnumber{2}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlfunctioncall{mean}\hlkeyword{(}\hlsymbol{x}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
 mean 
0.492 
\end{verbatim}
\end{kframe}}
\end{knitrout}

\end{solution}

\begin{problem}
Find the median of the random variable X, if it is exponentially distributed
with rate parameter 10.
\end{problem}
\begin{solution}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{qexp}\hlkeyword{(}\hlnumber{0.5}\hlkeyword{,}{\ }\hlnumber{10}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
[1] 0.0693
\end{verbatim}
\end{kframe}}
\end{knitrout}

\end{solution}


\section{Power Calculations}

\label{sec:onesamppower}

While not generally a major topic in introductory courses, power and sample size calculations
help to reinforce key ideas in statistics.  In this section, we will explore how \R\ can 
be used to undertake power calculations using analytic approaches (see \ref{sec:power}
for simulation based approaches).  We consider a simple problem with two tests (t-test and
sign test) of
a one-sided comparison.

Let $X_1, ..., X_{25}$ be i.i.d. $N(0.3, 1)$.  Consider testing the null hypothesis $H_0: \mu=0$ versus $H_A: \mu>0$ at significance level $\alpha=.05$.  Compare the power of the sign test and the power of the test based on normal theory (one sample one sided t-test) assuming that $\sigma$ 
is known.

\subsection{Sign test}

We first start by calculating the Type I error rate for the sign test.  Here we want to
reject when the number of positive values is large.  Under the null hypothesis, this is
distributed as a Binomial random variable with n=25 trials and p=0.5 probability of being
a positive value.  Let's consider values between 15 and 19.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{xvals}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlnumber{15}\hlkeyword{:}\hlnumber{19}\hspace*{\fill}\\
\hlstd{}\hlsymbol{probs}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlnumber{1}{\ }\hlkeyword{-}{\ }\hlfunctioncall{pbinom}\hlkeyword{(}\hlsymbol{xvals}\hlkeyword{,}{\ }\hlnumber{25}\hlkeyword{,}{\ }\hlnumber{0.5}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlfunctioncall{cbind}\hlkeyword{(}\hlsymbol{xvals}\hlkeyword{,}{\ }\hlsymbol{probs}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
     xvals   probs
[1,]    15 0.11476
[2,]    16 0.05388
[3,]    17 0.02164
[4,]    18 0.00732
[5,]    19 0.00204
\end{verbatim}
\end{kframe}}
\end{knitrout}

So we see that if we decide to reject when $X =$ the number of positive values is
17 or larger, we will have an $\alpha$ level of 0.054,
which is near the nominal value in the problem.

We calculate the power of the sign test as follows. The probability that $X > 0$, given that $H_A$ is true is given by:
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlnumber{1}{\ }\hlkeyword{-}{\ }\hlfunctioncall{pnorm}\hlkeyword{(}\hlnumber{0}\hlkeyword{,}{\ }\hlnumber{0.3}\hlkeyword{,}{\ }\hlnumber{1}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
[1] 0.618
\end{verbatim}
\end{kframe}}
\end{knitrout}

We can view this graphically using the command:

\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{xpnorm}\hlkeyword{(}\hlnumber{0}\hlkeyword{,}{\ }\hlnumber{0.3}\hlkeyword{,}{\ }\hlnumber{1}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}

If X ~ N(0.3,1), then 

	P(X <= 0) = P(Z <= -0.3) = 0.3821
	P(X >  0) = P(Z >  -0.3) = 0.6179

\end{verbatim}
\begin{verbatim}
[1] 0.382
\end{verbatim}


\centering{}\includegraphics{figures/fig-pnorm21} \includegraphics{figures/fig-pnorm22} 

\end{kframe}}
\end{knitrout}

\end{center}

So now we need to find the power under the alternative, which is equal to the probability of getting 17 or more positive values,
given that $p=0.6179$:
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlnumber{1}{\ }\hlkeyword{-}{\ }\hlfunctioncall{pbinom}\hlkeyword{(}\hlnumber{16}\hlkeyword{,}{\ }\hlnumber{25}\hlkeyword{,}{\ }\hlnumber{0.6179}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
[1] 0.338
\end{verbatim}
\end{kframe}}
\end{knitrout}


The power is modest at best.

\subsection{T-test}

We next calculate the power of the test based on normal theory.  To keep the comparison
fair, we will set our $\alpha$ level equal to 0.05388.
First we need to find the rejection region.  

\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{alpha}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlnumber{1}{\ }\hlkeyword{-}{\ }\hlfunctioncall{pbinom}\hlkeyword{(}\hlnumber{16}\hlkeyword{,}{\ }\hlnumber{25}\hlkeyword{,}{\ }\hlnumber{0.5}\hlkeyword{)}{\ }{\ }\hlcomment{\usebox{\hlnormalsizeboxhash}{\ }=={\ }0.0539,{\ }our{\ }alpha{\ }level.}\hspace*{\fill}\\
\hlstd{}\hlsymbol{n}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlnumber{25}\hspace*{\fill}\\
\hlstd{}\hlsymbol{sigma}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlnumber{1}{\ }{\ }\hlcomment{\usebox{\hlnormalsizeboxhash}{\ }given}\hspace*{\fill}\\
\hlstd{}\hlsymbol{stderr}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlfunctioncall{sqrt}\hlkeyword{(}\hlsymbol{sigma}\hlkeyword{\usebox{\hlnormalsizeboxhat}}\hlnumber{2}\hlkeyword{/}\hlsymbol{n}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlsymbol{zstar}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlfunctioncall{qnorm}\hlkeyword{(}\hlnumber{1}{\ }\hlkeyword{-}{\ }\hlsymbol{alpha}\hlkeyword{,}{\ }\hlnumber{0}\hlkeyword{,}{\ }\hlnumber{1}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlsymbol{zstar}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
[1] 1.61
\end{verbatim}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{crit}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlsymbol{zstar}{\ }\hlkeyword{*}{\ }\hlsymbol{stderr}\hspace*{\fill}\\
\hlstd{}\hlsymbol{crit}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
[1] 0.322
\end{verbatim}
\end{kframe}}
\end{knitrout}

Therefore, we reject for observed means greater than 0.322.  

To calculate the power of this one-sided test we find the area 
under the alternative hypothesis 
that is to the right of this cutoff:
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{power}{\ }\hlassignement{\usebox{\hlnormalsizeboxlessthan}-}{\ }\hlnumber{1}{\ }\hlkeyword{-}{\ }\hlfunctioncall{pnorm}\hlkeyword{(}\hlsymbol{crit}\hlkeyword{,}{\ }\hlnumber{0.3}\hlkeyword{,}{\ }\hlsymbol{stderr}\hlkeyword{)}\hspace*{\fill}\\
\hlstd{}\hlsymbol{power}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
[1] 0.457
\end{verbatim}
\end{kframe}}
\end{knitrout}

Thus, the power of the test based on normal theory is 0.457.
To provide a general check (or for future calculations of this sort) we can use the {\tt power.t.test()} in \R.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{power.t.test}\hlkeyword{(}\hlargument{n}{\ }\hlargument{=}{\ }\hlnumber{25}\hlkeyword{,}{\ }\hlargument{delta}{\ }\hlargument{=}{\ }\hlnumber{0.3}\hlkeyword{,}{\ }\hlargument{sd}{\ }\hlargument{=}{\ }\hlnumber{1}\hlkeyword{,}{\ }\hlargument{sig.level}{\ }\hlargument{=}{\ }\hlsymbol{alpha}\hlkeyword{,}{\ }\hlargument{alternative}{\ }\hlargument{=}{\ }\hlstring{"{}one.sided"{}}\hlkeyword{,}\hspace*{\fill}\\
\hlstd{}{\ }{\ }{\ }{\ }\hlargument{type}{\ }\hlargument{=}{\ }\hlstring{"{}one.sample"{}}\hlkeyword{)}\hlkeyword{\usebox{\hlnormalsizeboxdollar}}\hlsymbol{power}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
[1] 0.441
\end{verbatim}
\end{kframe}}
\end{knitrout}


This yields a similar estimate to the value that we calculated directly.  
Overall, we see that the t-test has higher power than the sign test, if the underlying
data are truly normal.  It's useful to have students calculate power empirically, 
as demonstrated for this example in \ref{sec:power}.

\begin{problem}
\label{prob:power1}


Find the power of a two-sided two-sample t-test where both distributions 
are approximately normally distributed with the same standard deviation, but the group differ by 50\% of the standard deviation.  Assume that there are 
100
observations per group and an alpha level of 0.01.

\end{problem}
\begin{solution}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{n}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
[1] 100
\end{verbatim}
\begin{flushleft}
\ttfamily\noindent
\hlsymbol{alpha}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}
[1] 0.01
\end{verbatim}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{power.t.test}\hlkeyword{(}\hlargument{n}{\ }\hlargument{=}{\ }\hlsymbol{n}\hlkeyword{,}{\ }\hlargument{delta}{\ }\hlargument{=}{\ }\hlnumber{0.5}\hlkeyword{,}{\ }\hlargument{sd}{\ }\hlargument{=}{\ }\hlnumber{1}\hlkeyword{,}{\ }\hlargument{sig.level}{\ }\hlargument{=}{\ }\hlsymbol{alpha}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}

     Two-sample t test power calculation 

              n = 100
          delta = 0.5
             sd = 1
      sig.level = 0.01
          power = 0.824
    alternative = two.sided

 NOTE: n is number in *each* group 

\end{verbatim}
\end{kframe}}
\end{knitrout}

\end{solution}

\begin{problem}
Repeat problem \ref{prob:power1} by simulating using the methods of section \ref{sec:power}.
\end{problem}

\begin{problem}
Find the sample size needed to have 90\% power for a two group t-test
where the true 
difference between means is 25\% of the standard deviation in the groups
(with $\alpha=0.05$).
\end{problem}
\begin{solution}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{.97, .97, .97}{\color{fgcolor}\begin{kframe}
\begin{flushleft}
\ttfamily\noindent
\hlfunctioncall{power.t.test}\hlkeyword{(}\hlargument{delta}{\ }\hlargument{=}{\ }\hlnumber{0.25}\hlkeyword{,}{\ }\hlargument{sd}{\ }\hlargument{=}{\ }\hlnumber{1}\hlkeyword{,}{\ }\hlargument{sig.level}{\ }\hlargument{=}{\ }\hlsymbol{alpha}\hlkeyword{,}{\ }\hlargument{power}{\ }\hlargument{=}{\ }\hlnumber{0.9}\hlkeyword{)}\mbox{}
\normalfont
\end{flushleft}
\begin{verbatim}

     Two-sample t test power calculation 

              n = 478
          delta = 0.25
             sd = 1
      sig.level = 0.01
          power = 0.9
    alternative = two.sided

 NOTE: n is number in *each* group 

\end{verbatim}
\end{kframe}}
\end{knitrout}

\end{solution}


\section{Exercises and Problems}

\shipoutProblems



