

\documentclass{article}
\begin{document}

\SweaveOpts{
tidy=TRUE,
dev=pdf,
fig.path=figures/fig-,  
fig.width=3, fig.height=2,
fig.align=center,
fig.show=hold,
comment=NA
}

<<setup,echo=FALSE,message=FALSE,results=hide>>=
source('setup.R')
@ 

<<>>=
f <- function(x) x^2
fplot(f,ylim=c(-1,4))
@

$f(x) = x (1-x)^2$ becomes
<<def-fun1>>=
f <- function(x) { x * (1-x)^2 }
@

<<>>=
f(1)
f(0:5)
@
<<>>=
fplot.default
@

<<>>=
xyplot(rnorm(10) ~ rnorm(10) )
@

\end{document}
